/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author surendra
 */
public class ClothesInfo extends javax.swing.JFrame {

    /**
     * Creates new form ClothesInfo
     */
    public ClothesInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        txtcomp = new javax.swing.JTextField();
        txtfabric = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        txtsize = new javax.swing.JTextField();
        info = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        txttype = new javax.swing.JTextField();
        fabeic = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        company = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        type = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        NO = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        lblrating = new javax.swing.JLabel();
        rating = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtreview = new javax.swing.JTextField();
        review = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submit.setBackground(new java.awt.Color(204, 255, 255));
        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        price.setText("Price");

        txtcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompActionPerformed(evt);
            }
        });

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        info.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        info.setForeground(new java.awt.Color(204, 0, 0));
        info.setText("CLOTHES INFO");

        size.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        size.setText("Size");

        gender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gender.setText("Gender");

        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });

        fabeic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fabeic.setText("Fabric");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        company.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        company.setText("Company");

        buttonGroup1.add(female);
        female.setText("Female");

        type.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        type.setText("Type");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Product ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fabeic)
                    .addComponent(company)
                    .addComponent(size)
                    .addComponent(gender)
                    .addComponent(price)
                    .addComponent(type)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(male)
                        .addGap(18, 18, 18)
                        .addComponent(female))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtcomp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfabric, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsize, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttype, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname))
                        .addGap(4, 4, 4)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(info)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(company)
                    .addComponent(txtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fabeic, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size)
                    .addComponent(txtsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(gender))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Value for money");

        buttonGroup1.add(yes);
        yes.setText("YES");

        buttonGroup1.add(NO);
        NO.setText("NO");

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("FINISH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblrating.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblrating.setText("Rating in star");

        rating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));
        rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Clothes Review");

        txtreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreviewActionPerformed(evt);
            }
        });

        review.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        review.setText("Review");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButton1)
                        .addGap(57, 57, 57)
                        .addComponent(submit)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtreview, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yes)
                                        .addGap(18, 18, 18)
                                        .addComponent(NO))
                                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(review)
                            .addComponent(jLabel3)
                            .addComponent(lblrating)
                            .addComponent(jLabel4))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(yes)
                            .addComponent(NO))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(review)
                            .addComponent(txtreview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrating))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
////        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
            Class<?> forName = Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/review?zeroDateTimeBehavior=convertToNull ","root","")) {
                String sql1="insert into product(P_Id,Name,Price,Company,Type) values (?,?,?,?,?)";
                String sql2="insert into clothes(P_Id,Fabric,Size,Gender) values (?,?,?,?)";
                String sql3="insert into reviews(Rating,Comment,Value_for_money,P_Id) values (?,?,?,?)";
                PreparedStatement pst1=con.prepareStatement(sql1);
                PreparedStatement pst2=con.prepareStatement(sql2);
                PreparedStatement pst3=con.prepareStatement(sql3);
                pst3.setInt(4,Integer.parseInt(txtpid.getText()));
                pst1.setInt(1,Integer.parseInt(txtpid.getText()));
                pst2.setInt(1,Integer.parseInt(txtpid.getText()));
                pst1.setString(2,txtname.getText());
                pst1.setInt(3,Integer.parseInt(txtprice.getText()));
                pst1.setString(4,txtcomp.getText());
                pst1.setString(5,txttype.getText());
                pst2.setString(2,txtfabric.getText());
                pst2.setString(3,txtsize.getText());
                
                String gend;
                if(male.isSelected()){
                    gend = male.getText();
                }
                else{
                    gend=female.getText();
                }
                pst2.setString(4, gend);
                
                pst3.setString(2,txtreview.getText());
                
                String value;
                if(yes.isSelected()){
                    value=yes.getText();
                }
                else{
                    value=NO.getText();
                }
                pst3.setString(3, value);
                
                
                String rate;
                rate=rating.getSelectedItem().toString();
                pst3.setString(1,rate);
                
                
                pst1.executeUpdate();
                pst2.executeUpdate();
                pst3.executeUpdate();
                JOptionPane.showMessageDialog(null,"INSERTION SUCCESSFUL");
               
            } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null,"Data Already Preasent") ;
             txtpid.setText("");
                txtname.setText("");
                txtcomp.setText("");
                txtprice.setText("");    
                txttype.setText("");
                txtfabric.setText("");
                txtsize.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(ClothesInfo.class.getName()).log(Level.SEVERE, null, ex);
            }    
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClothesInfo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
         }
        
        
        
        
        /*String p_id=txtpid.getText();
          String b=txtcomp.getText();
          String c=txtfabric.getText();
          String d=txtprice.getText();
          String e=txtsize.getText();
          String f=txttype.getText();
          String g=new String();
          if(male.isSelected())
              g ="Male";
          if(female.isSelected())
              g="Female";
          JOptionPane.showConfirmDialog(this,""+p_id+"\n"+b+"\n"+c+"\n"+d+"\n"+e+"\n"+f+"\n"+g);
          ClothesReview cl=new ClothesReview();
          cl.setVisible(true);
          this.dispose();*/
          
    }//GEN-LAST:event_submitActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
            if(male.isSelected())
                female.setSelected(false);
    }//GEN-LAST:event_maleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new Options().setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Options().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratingActionPerformed

    private void txtreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClothesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClothesInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel company;
    private javax.swing.JLabel fabeic;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblrating;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel price;
    private javax.swing.JComboBox<String> rating;
    private javax.swing.JLabel review;
    private javax.swing.JLabel size;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JTextField txtfabric;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtreview;
    private javax.swing.JTextField txtsize;
    private javax.swing.JTextField txttype;
    private javax.swing.JLabel type;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }

    private static class CothesReview {

        public CothesReview() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
